#!/bin/bash

# This is part of the chl project.
# Copyright (C) 2022
# Type chli on your Terminal for copying conditions.

echo What slot do you want to delete?
echo Valid answers: 1,2,3
read var
if [[ $var -gt 3 ]];
then
	echo Invalid answer.
else
	cd
	cd chc
	rm $var
fi
